on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Checkout Typst Packages Action
        uses: actions/checkout@v4
        with:
          repository: typst/packages
          ref: main
          path: ./.github/typst-action 
      - name: Typst Package Check
        uses: ./.github/typst-action/.github/actions/check 
        with:
          app-id: ${{ secrets.PACKAGE_CHECK_APP_ID }}
          installation-id: ${{ secrets.PACKAGE_CHECK_INSTALLATION_ID }}
          private-key: ${{ secrets.PACKAGE_CHECK_PRIVATE_KEY }}